### ISSUE TITLE
[Bug]Some MIDI Device cannot use in this version.

### ISSUE THREAD

**Issue by DFWJunior** [nhielost/obs-midi-mg#69] opened 2023-05-22 03:44 UTC
hi.
I have a home-made MIDI Controller.
recently i've found,when i plug this device into my computer,and i run OBS,it will crash immeditily.
seems like this version of OBS-MIDI-MG only cannot use in this device.
i tried my another MIDI controller,or didn't connet any device,it works fine.
what happened to my obs? thanks!

log will update later.

**Comment by KalamityStorm** [comment] 2023-05-22 03:52
[2023-05-22 11-49-17.txt](https://github.com/nhielost/obs-midi-mg/files/11526869/2023-05-22.11-49-17.txt)
this is the log when obs crashed.

[2023-05-22 11-50-47.txt](https://github.com/nhielost/obs-midi-mg/files/11526870/2023-05-22.11-50-47.txt)
this is a normal obs log.

i didn't configration anything then it crashed,so i think i don't need to update my config?
thanks!

**Comment by nhielost** [comment] 2023-06-05 14:49
Thanks for the feedback!

From looking at your logs, it looks like you are using an old version of the plugin. Try updating to version 2.3.0 and see what happens. (Don't try 2.3.1 as there are many confirmed bugs with that version.)

**Comment by ogmkp** [comment] 2023-10-25 09:57
Version 2.3.1 has been removed by the developer, so if you're good with it, please close this ticket.

**Comment by nhielost** [comment] 2024-02-18 21:17
This issue is being closed due to inactivity. Please create a new issue if it persists.

**Closed by nhielost** 2024-02-18 21:17 UTC
