### ISSUE TITLE
Crashing on Version 2.3.1

### ISSUE THREAD

**Issue by voxcityrp** [nhielost/obs-midi-mg#67] opened 2023-05-08 16:09 UTC
plugin keeps crashing on latest version of OBS 29.1.0 had to go back to v2.3.0 for the plugin to work. i have added crash report and log.

[2023-05-08 11-50-59.txt](https://github.com/nhielost/obs-midi-mg/files/11422762/2023-05-08.11-50-59.txt)
[Crash 2023-05-08 11-51-08.txt](https://github.com/nhielost/obs-midi-mg/files/11422764/Crash.2023-05-08.11-51-08.txt)

**Comment by basisbit** [comment] 2023-05-15 02:09
Can confirm the same issue and same workaround for OBS 29.0.2 on Windows 11

**Comment by malikbenkirane** [comment] 2023-06-01 16:22
alright it seems 2.3.1 doesn't work for a lot of people (#66 #65) and it crashes OBS Studio

Platform: Chip M1, $(arch)=arm64 and I confirmed OBS Studio is running on arm64 (no rosetta)

Surprisingly working with 2.3.0,
- I had first to remove `~/Library/Application Support/obs-studio/plugins/obs-midi-mg.plugin` 
- download release 2.3.0 and install

best luck with you guys!

**Comment by rayalitygaming** [comment] 2023-06-01 17:06
Im on PC. I tried 2.3 with same issues.  I didnt have issues 2 or 3 weeks
ago

**Comment by nhielost** [comment] 2023-06-05 14:34
Thanks for the feedback, and I'm sorry I've taken so long to respond.

I am aware of the issue, and it is a quick fix that should be out soon.

**Comment by ogmkp** [comment] 2023-10-25 09:57
Version 2.3.1 has been removed by the developer, so if you're good with it, please close this ticket.

**Comment by nhielost** [comment] 2024-02-18 21:13
This issue is being closed due to inactivity. Please create a new issue if it persists.

**Closed by nhielost** 2024-02-18 21:13 UTC
